baseURL = 'https://rustated.com'
languageCode = 'en-us'
title = 'Rustated'
theme = 'terminal'

paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Rustated"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Rustated"
      logoHomeLink = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
